App:
  WorkingDirectory: var/
  MaxUsers: 1
  AllowRegistration: true
  MaxNickLen: 15
  MenuMaxIdleTime: 600

Menus:
  anonymous:
    MenuEntries:
      - Key: t
        Label: test
        Action: menu test
  logged_in:
    MenuEntries:
      - Key: q
        Label: quit
        Action: quit
  test:
    MenuEntries:
      - Key: q
        Label: quit
        Action: quit
  test:
    MenuEntries:
      - Key: a
        Label: login
        Action: login
