App:
  WorkingDirectory: var/
  MaxUsers: 1
  AllowRegistration: true
  MaxNickLen: 15
  MenuMaxIdleTime: 600

Menus:
  anonymous:
    MenuEntries:
      - Key: q
        Label: quit
        Action: quit
  test:
    MenuEntries:
      - Key: q
        Label: quit
        Action: quit
