App:
  WorkingDirectory: var/
  MaxUsers: 1
  AllowRegistration: true
  MaxNickLen: 15
  MenuMaxIdleTime: 600

Menus:
  anonymous:
    MenuEntries:
      - Key: q
        Label: quit
        Action: quit
  logged_in:
    MenuEntries:
      - Key: p
        Label: play
        Action: play test

Games:
  test:
    ChrootPath: test_data/fake_nethack_directory
    FileMode:   0777
    Commands:
      - wait
  test:
    ChrootPath: test_data/fake_nethack_directory
    FileMode:   0777
    Commands:
      - wait
