App:
  WorkingDirectory: var/
  MaxUsers: 1
  AllowRegistration: true
  MaxNickLen: 15
  MenuMaxIdleTime: 600

Menus:
  anonymous:
    MenuEntries:
      - Key: q
        Label: quit
        Action: quit
  logged_in:
    MenuEntries:
      - Key: q
        Label: quit
        Action: quit

Games:
  unreachable:
